# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FTSDKiOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FTSDKiOSDemo
   pod 'FTMobileAgent', '~>1.0.0-alpha.5'
end
