# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dataflux-sdk-ios-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for dataflux-sdk-ios-demo
  pod 'FTMobileSDK', '~>1.3.3-alpha.2'

end
